// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/server/drive/:folder_id/download": {
    params: {
      "folder_id": string;
    };
  };
  "/public/design-link/:domain": {
    params: {
      "domain": string;
    };
  };
  "/public/drive-link/:domain": {
    params: {
      "domain": string;
    };
  };
  "/resources/image-proxy": {
    params: {};
  };
  "/dashboard/customer": {
    params: {};
  };
  "/media/event/:slug": {
    params: {
      "slug": string;
    };
  };
  "/logout": {
    params: {};
  };
  "/api/nexus": {
    params: {};
  };
  "/api/nexus/example": {
    params: {};
  };
  "/api/nexus/demo": {
    params: {};
  };
  "/katalog": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/finance/salary-employee": {
    params: {};
  };
  "/app/procurement/:category": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/catalog-color": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/shopping-kaos": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/component": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/capacity": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/shopping": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/supplier": {
    params: {
      "category": string;
    };
  };
  "/app/procurement/:category/vendor": {
    params: {
      "category": string;
    };
  };
  "/app/orders/:id/download": {
    params: {
      "id": string;
    };
  };
  "/app/setting/recycle-bin": {
    params: {};
  };
  "/app/master/institution": {
    params: {};
  };
  "/app/finance/inventory": {
    params: {};
  };
  "/app/finance/cashflow": {
    params: {};
  };
  "/app/asset/inventory": {
    params: {};
  };
  "/app/finance/account": {
    params: {};
  };
  "/app/master/supplier": {
    params: {};
  };
  "/app/setting/account": {
    params: {};
  };
  "/app/finance": {
    params: {};
  };
  "/app/order-edit/:id": {
    params: {
      "id": string;
    };
  };
  "/app/setting/design": {
    params: {};
  };
  "/app/order-history": {
    params: {};
  };
  "/app/order-manage": {
    params: {};
  };
  "/app/product-list": {
    params: {};
  };
  "/app/order-form": {
    params: {};
  };
  "/app/order-list": {
    params: {};
  };
  "/app/print-area": {
    params: {};
  };
  "/app/overview": {
    params: {};
  };
  "/app/drive": {
    params: {};
  };
  "/app/drive/customer": {
    params: {};
  };
  "/app/drive/internal": {
    params: {};
  };
  "/app/email": {
    params: {};
  };
  "/app/user": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/server/drive/:folder_id/download" | "/public/design-link/:domain" | "/public/drive-link/:domain" | "/resources/image-proxy" | "/dashboard/customer" | "/media/event/:slug" | "/logout" | "/api/nexus" | "/api/nexus/example" | "/api/nexus/demo" | "/katalog" | "/login" | "/app" | "/app/finance/salary-employee" | "/app/procurement/:category" | "/app/procurement/:category/catalog-color" | "/app/procurement/:category/shopping-kaos" | "/app/procurement/:category/component" | "/app/procurement/:category/capacity" | "/app/procurement/:category/shopping" | "/app/procurement/:category/supplier" | "/app/procurement/:category/vendor" | "/app/orders/:id/download" | "/app/setting/recycle-bin" | "/app/master/institution" | "/app/finance/inventory" | "/app/finance/cashflow" | "/app/asset/inventory" | "/app/finance/account" | "/app/master/supplier" | "/app/setting/account" | "/app/finance" | "/app/order-edit/:id" | "/app/setting/design" | "/app/order-history" | "/app/order-manage" | "/app/product-list" | "/app/order-form" | "/app/order-list" | "/app/print-area" | "/app/overview" | "/app/drive" | "/app/drive/customer" | "/app/drive/internal" | "/app/email" | "/app/user";
  };
  "routes/server.drive.$folder_id.download.tsx": {
    id: "routes/server.drive.$folder_id.download";
    page: "/server/drive/:folder_id/download";
  };
  "routes/public.design-link.$domain.tsx": {
    id: "routes/public.design-link.$domain";
    page: "/public/design-link/:domain";
  };
  "routes/public.drive-link.$domain.tsx": {
    id: "routes/public.drive-link.$domain";
    page: "/public/drive-link/:domain";
  };
  "routes/resources.image-proxy.tsx": {
    id: "routes/resources.image-proxy";
    page: "/resources/image-proxy";
  };
  "routes/dashboard.customer.tsx": {
    id: "routes/dashboard.customer";
    page: "/dashboard/customer";
  };
  "routes/media.event.$slug.tsx": {
    id: "routes/media.event.$slug";
    page: "/media/event/:slug";
  };
  "routes/_auth.logout.tsx": {
    id: "routes/_auth.logout";
    page: "/logout";
  };
  "routes/api.nexus.tsx": {
    id: "routes/api.nexus";
    page: "/api/nexus" | "/api/nexus/example" | "/api/nexus/demo";
  };
  "routes/api.nexus.example.tsx": {
    id: "routes/api.nexus.example";
    page: "/api/nexus/example";
  };
  "routes/api.nexus.demo.tsx": {
    id: "routes/api.nexus.demo";
    page: "/api/nexus/demo";
  };
  "routes/katalog.tsx": {
    id: "routes/katalog";
    page: "/katalog";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/finance/salary-employee" | "/app/procurement/:category" | "/app/procurement/:category/catalog-color" | "/app/procurement/:category/shopping-kaos" | "/app/procurement/:category/component" | "/app/procurement/:category/capacity" | "/app/procurement/:category/shopping" | "/app/procurement/:category/supplier" | "/app/procurement/:category/vendor" | "/app/orders/:id/download" | "/app/setting/recycle-bin" | "/app/master/institution" | "/app/finance/inventory" | "/app/finance/cashflow" | "/app/asset/inventory" | "/app/finance/account" | "/app/master/supplier" | "/app/setting/account" | "/app/finance" | "/app/order-edit/:id" | "/app/setting/design" | "/app/order-history" | "/app/order-manage" | "/app/product-list" | "/app/order-form" | "/app/order-list" | "/app/print-area" | "/app/overview" | "/app/drive" | "/app/drive/customer" | "/app/drive/internal" | "/app/email" | "/app/user";
  };
  "routes/app.finance.salary-employee.tsx": {
    id: "routes/app.finance.salary-employee";
    page: "/app/finance/salary-employee";
  };
  "routes/app.procurement.$category.tsx": {
    id: "routes/app.procurement.$category";
    page: "/app/procurement/:category" | "/app/procurement/:category/catalog-color" | "/app/procurement/:category/shopping-kaos" | "/app/procurement/:category/component" | "/app/procurement/:category/capacity" | "/app/procurement/:category/shopping" | "/app/procurement/:category/supplier" | "/app/procurement/:category/vendor";
  };
  "routes/app.procurement.$category.catalog-color.tsx": {
    id: "routes/app.procurement.$category.catalog-color";
    page: "/app/procurement/:category/catalog-color";
  };
  "routes/app.procurement.$category.shopping-kaos.tsx": {
    id: "routes/app.procurement.$category.shopping-kaos";
    page: "/app/procurement/:category/shopping-kaos";
  };
  "routes/app.procurement.$category.component.tsx": {
    id: "routes/app.procurement.$category.component";
    page: "/app/procurement/:category/component";
  };
  "routes/app.procurement.$category.capacity.tsx": {
    id: "routes/app.procurement.$category.capacity";
    page: "/app/procurement/:category/capacity";
  };
  "routes/app.procurement.$category.shopping.tsx": {
    id: "routes/app.procurement.$category.shopping";
    page: "/app/procurement/:category/shopping";
  };
  "routes/app.procurement.$category.supplier.tsx": {
    id: "routes/app.procurement.$category.supplier";
    page: "/app/procurement/:category/supplier";
  };
  "routes/app.procurement.$category.vendor.tsx": {
    id: "routes/app.procurement.$category.vendor";
    page: "/app/procurement/:category/vendor";
  };
  "routes/app.orders.$id.download.tsx": {
    id: "routes/app.orders.$id.download";
    page: "/app/orders/:id/download";
  };
  "routes/app.setting.recycle-bin.tsx": {
    id: "routes/app.setting.recycle-bin";
    page: "/app/setting/recycle-bin";
  };
  "routes/app.master.institution.tsx": {
    id: "routes/app.master.institution";
    page: "/app/master/institution";
  };
  "routes/app.finance.inventory.tsx": {
    id: "routes/app.finance.inventory";
    page: "/app/finance/inventory";
  };
  "routes/app.finance.cashflow.tsx": {
    id: "routes/app.finance.cashflow";
    page: "/app/finance/cashflow";
  };
  "routes/app.asset.inventory.tsx": {
    id: "routes/app.asset.inventory";
    page: "/app/asset/inventory";
  };
  "routes/app.finance.account.tsx": {
    id: "routes/app.finance.account";
    page: "/app/finance/account";
  };
  "routes/app.master.supplier.tsx": {
    id: "routes/app.master.supplier";
    page: "/app/master/supplier";
  };
  "routes/app.setting.account.tsx": {
    id: "routes/app.setting.account";
    page: "/app/setting/account";
  };
  "routes/app.finance._index.tsx": {
    id: "routes/app.finance._index";
    page: "/app/finance";
  };
  "routes/app.order-edit.$id.tsx": {
    id: "routes/app.order-edit.$id";
    page: "/app/order-edit/:id";
  };
  "routes/app.setting.design.tsx": {
    id: "routes/app.setting.design";
    page: "/app/setting/design";
  };
  "routes/app.order-history.tsx": {
    id: "routes/app.order-history";
    page: "/app/order-history";
  };
  "routes/app.order-manage.tsx": {
    id: "routes/app.order-manage";
    page: "/app/order-manage";
  };
  "routes/app.product-list.tsx": {
    id: "routes/app.product-list";
    page: "/app/product-list";
  };
  "routes/app.order-form.tsx": {
    id: "routes/app.order-form";
    page: "/app/order-form";
  };
  "routes/app.order-list.tsx": {
    id: "routes/app.order-list";
    page: "/app/order-list";
  };
  "routes/app.print-area.tsx": {
    id: "routes/app.print-area";
    page: "/app/print-area";
  };
  "routes/app.overview.tsx": {
    id: "routes/app.overview";
    page: "/app/overview";
  };
  "routes/app.drive.tsx": {
    id: "routes/app.drive";
    page: "/app/drive" | "/app/drive/customer" | "/app/drive/internal";
  };
  "routes/app.drive.customer.tsx": {
    id: "routes/app.drive.customer";
    page: "/app/drive/customer";
  };
  "routes/app.drive.internal.tsx": {
    id: "routes/app.drive.internal";
    page: "/app/drive/internal";
  };
  "routes/app.email.tsx": {
    id: "routes/app.email";
    page: "/app/email";
  };
  "routes/app.user.tsx": {
    id: "routes/app.user";
    page: "/app/user";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/server.drive.$folder_id.download": typeof import("./app/routes/server.drive.$folder_id.download.tsx");
  "routes/public.design-link.$domain": typeof import("./app/routes/public.design-link.$domain.tsx");
  "routes/public.drive-link.$domain": typeof import("./app/routes/public.drive-link.$domain.tsx");
  "routes/resources.image-proxy": typeof import("./app/routes/resources.image-proxy.tsx");
  "routes/dashboard.customer": typeof import("./app/routes/dashboard.customer.tsx");
  "routes/media.event.$slug": typeof import("./app/routes/media.event.$slug.tsx");
  "routes/_auth.logout": typeof import("./app/routes/_auth.logout.tsx");
  "routes/api.nexus": typeof import("./app/routes/api.nexus.tsx");
  "routes/api.nexus.example": typeof import("./app/routes/api.nexus.example.tsx");
  "routes/api.nexus.demo": typeof import("./app/routes/api.nexus.demo.tsx");
  "routes/katalog": typeof import("./app/routes/katalog.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.finance.salary-employee": typeof import("./app/routes/app.finance.salary-employee.tsx");
  "routes/app.procurement.$category": typeof import("./app/routes/app.procurement.$category.tsx");
  "routes/app.procurement.$category.catalog-color": typeof import("./app/routes/app.procurement.$category.catalog-color.tsx");
  "routes/app.procurement.$category.shopping-kaos": typeof import("./app/routes/app.procurement.$category.shopping-kaos.tsx");
  "routes/app.procurement.$category.component": typeof import("./app/routes/app.procurement.$category.component.tsx");
  "routes/app.procurement.$category.capacity": typeof import("./app/routes/app.procurement.$category.capacity.tsx");
  "routes/app.procurement.$category.shopping": typeof import("./app/routes/app.procurement.$category.shopping.tsx");
  "routes/app.procurement.$category.supplier": typeof import("./app/routes/app.procurement.$category.supplier.tsx");
  "routes/app.procurement.$category.vendor": typeof import("./app/routes/app.procurement.$category.vendor.tsx");
  "routes/app.orders.$id.download": typeof import("./app/routes/app.orders.$id.download.tsx");
  "routes/app.setting.recycle-bin": typeof import("./app/routes/app.setting.recycle-bin.tsx");
  "routes/app.master.institution": typeof import("./app/routes/app.master.institution.tsx");
  "routes/app.finance.inventory": typeof import("./app/routes/app.finance.inventory.tsx");
  "routes/app.finance.cashflow": typeof import("./app/routes/app.finance.cashflow.tsx");
  "routes/app.asset.inventory": typeof import("./app/routes/app.asset.inventory.tsx");
  "routes/app.finance.account": typeof import("./app/routes/app.finance.account.tsx");
  "routes/app.master.supplier": typeof import("./app/routes/app.master.supplier.tsx");
  "routes/app.setting.account": typeof import("./app/routes/app.setting.account.tsx");
  "routes/app.finance._index": typeof import("./app/routes/app.finance._index.tsx");
  "routes/app.order-edit.$id": typeof import("./app/routes/app.order-edit.$id.tsx");
  "routes/app.setting.design": typeof import("./app/routes/app.setting.design.tsx");
  "routes/app.order-history": typeof import("./app/routes/app.order-history.tsx");
  "routes/app.order-manage": typeof import("./app/routes/app.order-manage.tsx");
  "routes/app.product-list": typeof import("./app/routes/app.product-list.tsx");
  "routes/app.order-form": typeof import("./app/routes/app.order-form.tsx");
  "routes/app.order-list": typeof import("./app/routes/app.order-list.tsx");
  "routes/app.print-area": typeof import("./app/routes/app.print-area.tsx");
  "routes/app.overview": typeof import("./app/routes/app.overview.tsx");
  "routes/app.drive": typeof import("./app/routes/app.drive.tsx");
  "routes/app.drive.customer": typeof import("./app/routes/app.drive.customer.tsx");
  "routes/app.drive.internal": typeof import("./app/routes/app.drive.internal.tsx");
  "routes/app.email": typeof import("./app/routes/app.email.tsx");
  "routes/app.user": typeof import("./app/routes/app.user.tsx");
};